### ISSUE TITLE
Entity threw exception

### ISSUE THREAD

**Issue by Fargus5** [BalrogGames/Technical-Support#47]
```
[22:15:11]: [INFO] Fargus issued server command: /fm spawn archer
[22:15:12]: [WARN] Entity threw exception at world:-248.29468968701593,65.0,354.7524392824454
[22:15:12]: [WARN] java.lang.NullPointerException
[22:15:12]: [WARN] at net.minecraft.server.v1_15_R1.Entity.getBukkitEntity(Entity.java:86)
[22:15:12]: [WARN] at net.minecraft.server.v1_15_R1.NavigationAbstract.a(NavigationAbstract.java:127)
[22:15:12]: [WARN] at net.minecraft.server.v1_15_R1.NavigationAbstract.a(NavigationAbstract.java:98)
[22:15:12]: [WARN] at net.minecraft.server.v1_15_R1.Navigation.a(Navigation.java:63)
[22:15:12]: [WARN] at net.minecraft.server.v1_15_R1.NavigationAbstract.a(NavigationAbstract.java:172)
[22:15:12]: [WARN] at com.gmail.scyntrus.fmob.mobs.Archer.movementTick(Archer.java:154)
[22:15:12]: [WARN] at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2396)
[22:15:12]: [WARN] at net.minecraft.server.v1_15_R1.EntityInsentient.tick(EntityInsentient.java:288)
[22:15:12]: [WARN] at com.gmail.scyntrus.fmob.mobs.Archer.tick(Archer.java:504)
[22:15:12]: [WARN] at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:803)
[22:15:12]: [WARN] at net.minecraft.server.v1_15_R1.World.a(World.java:869)
[22:15:12]: [WARN] at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:528)
[22:15:12]: [WARN] at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1303)
[22:15:12]: [WARN] at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[22:15:12]: [WARN] at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1157)
[22:15:12]: [WARN] at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946)
[22:15:12]: [WARN] at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Fargus5** [comment]
```
[20:30:47]: [INFO] Fargus issued server command: /fm spawn archer
[20:30:49]: [WARN] Entity threw exception at Europe:-1117.0229798531623,65.0,538.3324278043892
[20:30:49]: [WARN] java.lang.NullPointerException
[20:30:49]: [WARN] at net.minecraft.server.v1_15_R1.Entity.getBukkitEntity(Entity.java:86)
[20:30:49]: [WARN] at net.minecraft.server.v1_15_R1.NavigationAbstract.a(NavigationAbstract.java:127)
[20:30:49]: [WARN] at net.minecraft.server.v1_15_R1.NavigationAbstract.a(NavigationAbstract.java:98)
[20:30:49]: [WARN] at net.minecraft.server.v1_15_R1.Navigation.a(Navigation.java:63)
[20:30:49]: [WARN] at net.minecraft.server.v1_15_R1.NavigationAbstract.a(NavigationAbstract.java:172)
[20:30:49]: [WARN] at com.gmail.scyntrus.fmob.mobs.Archer.movementTick(Archer.java:154)
[20:30:49]: [WARN] at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2396)
[20:30:49]: [WARN] at net.minecraft.server.v1_15_R1.EntityInsentient.tick(EntityInsentient.java:288)
[20:30:49]: [WARN] at com.gmail.scyntrus.fmob.mobs.Archer.tick(Archer.java:504)
[20:30:49]: [WARN] at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:803)
[20:30:49]: [WARN] at net.minecraft.server.v1_15_R1.World.a(World.java:869)
[20:30:49]: [WARN] at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:528)
[20:30:49]: [WARN] at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1303)
[20:30:49]: [WARN] at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[20:30:49]: [WARN] at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1157)
[20:30:49]: [WARN] at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946)
[20:30:49]: [WARN] at java.base/java.lang.Thread.run(Thread.java:834)

```
